### PR TITLE
Update to python 3.9

### PR DESCRIPTION
**Pull request by DBurkhead**
Update AP Lambda from python 3.6 to python 3.9.

*Description of changes:*
Update Lambda based on Python 3.6 EOL.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by DBurkhead** [comment]
Just noticed that this was never merged. @vsnyc can you or someone else on the aws-quickstart team merge this pull request?

**Comment by DBurkhead** [comment]
@vsnyc do I added a .metadata file to the pull request. I just copied the contents of the referenced file. Let me know if it needs to be updated.

**Comment by vsnyc** [comment]
@DBurkhead - thanks! That should be sufficient, we'll get some feedback on the PR whether the automated tests passed or not in a bit.

**Review by vsnyc — APPROVED** [review]
Tests passed in CI

**Pull request merged**
