### PR TITLE
Discard kinesis records that don't match the Agent Event JSON format.

### PR DESCRIPTION
**Pull request by DBurkhead**
Discard kinesis records that don't match the Agent Event JSON format.  This change is intended to handle the case of configuring both Agent Events and Contact Trace Records to feed into the same kinesis stream. Contact Trace Records will be discarded.

*Issue #12 

If there are errors deserializing the JSON of a kinesis event or if the kinesis event doesn't include an AgentARN top-level property, don't send the event to the DynamoDB table and SQS.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by DBurkhead** [comment]
In the past, the aws-quickstart team has rebuilt the .zip containing the binaries for this Lambda. Let me know if I need to include an updated .zip in the pull request.

**Comment by DBurkhead** [comment]
@andrew-glenn Not sure if you're the right person to ask about this. Let me know if I should contact someone else. Can someone on the aws-quickstart team take a look at this pull request? This is a fix for an issue we've seen in the past when you configure both Agent Events and Contact Trace Records to feed into the kinesis stream used by the Real-Time Adherence integration. This change adds some logic to the RTA Lambda that discards contact trace records. Previously, the Lambda would get an exception processing the contact trace record and then get hung up retrying that record, blocking state changes from being processed.

**Comment by andrew-glenn** [comment]
@DBurkhead Thanks for the ping. Approved. If you can quickly rebuild the zip, that's super appreciated. Otherwise it'll be delayed a little bit on my end.

**Comment by DBurkhead** [comment]
@andrew-glenn OK, I updated the zip and pushed that commit. Thanks for the help

**Pull request merged**
